// @ts-nocheck
// eslint-disable
// This file is generated by create-validator-ts
import Ajv from 'ajv';
import type * as apiTypes from './tjs-type-annotation';

export const SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/UpdateUser",
    "definitions": {
        "UpdateUser": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "pattern": "[a-z]{3,}"
                },
                "age": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "id",
                "age"
            ],
            "additionalProperties": false
        }
    }
};
const ajv = new Ajv({ removeAdditional: true }).addSchema(SCHEMA, "SCHEMA");
export function validateUpdateUser(payload: unknown): apiTypes.UpdateUser {
  /** Schema is defined in {@link SCHEMA.definitions.UpdateUser } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/UpdateUser");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid UpdateUser: ' + ajv.errorsText(validator.errors, {dataVar: "UpdateUser"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isUpdateUser(payload: unknown): payload is apiTypes.UpdateUser {
  try {
    validateUpdateUser(payload);
    return true;
  } catch (error) {
    return false;
  }
}
