// @ts-nocheck
// eslint-disable
// This file is generated by create-validator-ts
import Ajv from 'ajv';
import * as apiTypes from './tjs-type-annotation';

const SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/UpdateUser",
    "definitions": {
        "UpdateUser": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "pattern": "/[a-z]{4}/"
                },
                "age": {
                    "type": "number",
                    "minimum": 0
                }
            },
            "required": [
                "id",
                "age"
            ],
            "additionalProperties": false
        }
    }
};
const ajv = new Ajv({ removeAdditional: true }).addSchema(SCHEMA, "SCHEMA");
export function validateUpdateUser(payload: unknown): apiTypes.UpdateUser {
  if (!isUpdateUser(payload)) {
    const error = new Error('invalid payload: UpdateUser');
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isUpdateUser(payload: unknown): payload is apiTypes.UpdateUser {
  /** Schema is defined in {@link SCHEMA.definitions.UpdateUser } **/
  const ajvValidate = ajv.compile({ "$ref": "SCHEMA#/definitions/UpdateUser" });
  return ajvValidate(payload);
}
